version: 2
updates:
  - package-ecosystem: "pip"
    directory: "/"         # ubicaci√≥n de requirements.txt
    schedule:
      interval: "daily"    # opciones: "daily", "weekly", "monthly"
    open-pull-requests-limit: 5
    # optionally:
    # allowed:
    #   - dependency-type: "all"
